title: Eddy's Online Resume
logo: /assets/img/logo1.png
description: Diablo-Physics-Phylum
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
cv: /assets/document/Eddy_Resume_Dell.pdf
