title: Eddy's Online Resume
logo: /assets/img/logo1.png
description: Standing upon the shoulders of the giants which stands on the top of the world
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
cv: /assets/document/Eddy_Resume_Dell.pdf
description2: Diablo-Physics-Phylum
